# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/blackhatmonkey/workspace/oss/maze_runner

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/blackhatmonkey/workspace/oss/maze_runner

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/blackhatmonkey/workspace/oss/maze_runner/CMakeFiles /home/blackhatmonkey/workspace/oss/maze_runner/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/blackhatmonkey/workspace/oss/maze_runner/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named maze_runner_test

# Build rule for target.
maze_runner_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 maze_runner_test
.PHONY : maze_runner_test

# fast build rule for target.
maze_runner_test/fast:
	$(MAKE) -f CMakeFiles/maze_runner_test.dir/build.make CMakeFiles/maze_runner_test.dir/build
.PHONY : maze_runner_test/fast

#=============================================================================
# Target rules for targets named disjointset_tester

# Build rule for target.
disjointset_tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 disjointset_tester
.PHONY : disjointset_tester

# fast build rule for target.
disjointset_tester/fast:
	$(MAKE) -f CMakeFiles/disjointset_tester.dir/build.make CMakeFiles/disjointset_tester.dir/build
.PHONY : disjointset_tester/fast

#=============================================================================
# Target rules for targets named maze_generator_test

# Build rule for target.
maze_generator_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 maze_generator_test
.PHONY : maze_generator_test

# fast build rule for target.
maze_generator_test/fast:
	$(MAKE) -f CMakeFiles/maze_generator_test.dir/build.make CMakeFiles/maze_generator_test.dir/build
.PHONY : maze_generator_test/fast

disjointset.o: disjointset.cpp.o

.PHONY : disjointset.o

# target to build an object file
disjointset.cpp.o:
	$(MAKE) -f CMakeFiles/disjointset_tester.dir/build.make CMakeFiles/disjointset_tester.dir/disjointset.cpp.o
	$(MAKE) -f CMakeFiles/maze_generator_test.dir/build.make CMakeFiles/maze_generator_test.dir/disjointset.cpp.o
.PHONY : disjointset.cpp.o

disjointset.i: disjointset.cpp.i

.PHONY : disjointset.i

# target to preprocess a source file
disjointset.cpp.i:
	$(MAKE) -f CMakeFiles/disjointset_tester.dir/build.make CMakeFiles/disjointset_tester.dir/disjointset.cpp.i
	$(MAKE) -f CMakeFiles/maze_generator_test.dir/build.make CMakeFiles/maze_generator_test.dir/disjointset.cpp.i
.PHONY : disjointset.cpp.i

disjointset.s: disjointset.cpp.s

.PHONY : disjointset.s

# target to generate assembly for a file
disjointset.cpp.s:
	$(MAKE) -f CMakeFiles/disjointset_tester.dir/build.make CMakeFiles/disjointset_tester.dir/disjointset.cpp.s
	$(MAKE) -f CMakeFiles/maze_generator_test.dir/build.make CMakeFiles/maze_generator_test.dir/disjointset.cpp.s
.PHONY : disjointset.cpp.s

disjointset_test.o: disjointset_test.cpp.o

.PHONY : disjointset_test.o

# target to build an object file
disjointset_test.cpp.o:
	$(MAKE) -f CMakeFiles/disjointset_tester.dir/build.make CMakeFiles/disjointset_tester.dir/disjointset_test.cpp.o
.PHONY : disjointset_test.cpp.o

disjointset_test.i: disjointset_test.cpp.i

.PHONY : disjointset_test.i

# target to preprocess a source file
disjointset_test.cpp.i:
	$(MAKE) -f CMakeFiles/disjointset_tester.dir/build.make CMakeFiles/disjointset_tester.dir/disjointset_test.cpp.i
.PHONY : disjointset_test.cpp.i

disjointset_test.s: disjointset_test.cpp.s

.PHONY : disjointset_test.s

# target to generate assembly for a file
disjointset_test.cpp.s:
	$(MAKE) -f CMakeFiles/disjointset_tester.dir/build.make CMakeFiles/disjointset_tester.dir/disjointset_test.cpp.s
.PHONY : disjointset_test.cpp.s

maze.o: maze.cpp.o

.PHONY : maze.o

# target to build an object file
maze.cpp.o:
	$(MAKE) -f CMakeFiles/maze_runner_test.dir/build.make CMakeFiles/maze_runner_test.dir/maze.cpp.o
.PHONY : maze.cpp.o

maze.i: maze.cpp.i

.PHONY : maze.i

# target to preprocess a source file
maze.cpp.i:
	$(MAKE) -f CMakeFiles/maze_runner_test.dir/build.make CMakeFiles/maze_runner_test.dir/maze.cpp.i
.PHONY : maze.cpp.i

maze.s: maze.cpp.s

.PHONY : maze.s

# target to generate assembly for a file
maze.cpp.s:
	$(MAKE) -f CMakeFiles/maze_runner_test.dir/build.make CMakeFiles/maze_runner_test.dir/maze.cpp.s
.PHONY : maze.cpp.s

maze_generator.o: maze_generator.cpp.o

.PHONY : maze_generator.o

# target to build an object file
maze_generator.cpp.o:
	$(MAKE) -f CMakeFiles/maze_generator_test.dir/build.make CMakeFiles/maze_generator_test.dir/maze_generator.cpp.o
.PHONY : maze_generator.cpp.o

maze_generator.i: maze_generator.cpp.i

.PHONY : maze_generator.i

# target to preprocess a source file
maze_generator.cpp.i:
	$(MAKE) -f CMakeFiles/maze_generator_test.dir/build.make CMakeFiles/maze_generator_test.dir/maze_generator.cpp.i
.PHONY : maze_generator.cpp.i

maze_generator.s: maze_generator.cpp.s

.PHONY : maze_generator.s

# target to generate assembly for a file
maze_generator.cpp.s:
	$(MAKE) -f CMakeFiles/maze_generator_test.dir/build.make CMakeFiles/maze_generator_test.dir/maze_generator.cpp.s
.PHONY : maze_generator.cpp.s

maze_generator_test.o: maze_generator_test.cpp.o

.PHONY : maze_generator_test.o

# target to build an object file
maze_generator_test.cpp.o:
	$(MAKE) -f CMakeFiles/maze_generator_test.dir/build.make CMakeFiles/maze_generator_test.dir/maze_generator_test.cpp.o
.PHONY : maze_generator_test.cpp.o

maze_generator_test.i: maze_generator_test.cpp.i

.PHONY : maze_generator_test.i

# target to preprocess a source file
maze_generator_test.cpp.i:
	$(MAKE) -f CMakeFiles/maze_generator_test.dir/build.make CMakeFiles/maze_generator_test.dir/maze_generator_test.cpp.i
.PHONY : maze_generator_test.cpp.i

maze_generator_test.s: maze_generator_test.cpp.s

.PHONY : maze_generator_test.s

# target to generate assembly for a file
maze_generator_test.cpp.s:
	$(MAKE) -f CMakeFiles/maze_generator_test.dir/build.make CMakeFiles/maze_generator_test.dir/maze_generator_test.cpp.s
.PHONY : maze_generator_test.cpp.s

maze_runner.o: maze_runner.cpp.o

.PHONY : maze_runner.o

# target to build an object file
maze_runner.cpp.o:
	$(MAKE) -f CMakeFiles/maze_runner_test.dir/build.make CMakeFiles/maze_runner_test.dir/maze_runner.cpp.o
.PHONY : maze_runner.cpp.o

maze_runner.i: maze_runner.cpp.i

.PHONY : maze_runner.i

# target to preprocess a source file
maze_runner.cpp.i:
	$(MAKE) -f CMakeFiles/maze_runner_test.dir/build.make CMakeFiles/maze_runner_test.dir/maze_runner.cpp.i
.PHONY : maze_runner.cpp.i

maze_runner.s: maze_runner.cpp.s

.PHONY : maze_runner.s

# target to generate assembly for a file
maze_runner.cpp.s:
	$(MAKE) -f CMakeFiles/maze_runner_test.dir/build.make CMakeFiles/maze_runner_test.dir/maze_runner.cpp.s
.PHONY : maze_runner.cpp.s

maze_runner_test.o: maze_runner_test.cpp.o

.PHONY : maze_runner_test.o

# target to build an object file
maze_runner_test.cpp.o:
	$(MAKE) -f CMakeFiles/maze_runner_test.dir/build.make CMakeFiles/maze_runner_test.dir/maze_runner_test.cpp.o
.PHONY : maze_runner_test.cpp.o

maze_runner_test.i: maze_runner_test.cpp.i

.PHONY : maze_runner_test.i

# target to preprocess a source file
maze_runner_test.cpp.i:
	$(MAKE) -f CMakeFiles/maze_runner_test.dir/build.make CMakeFiles/maze_runner_test.dir/maze_runner_test.cpp.i
.PHONY : maze_runner_test.cpp.i

maze_runner_test.s: maze_runner_test.cpp.s

.PHONY : maze_runner_test.s

# target to generate assembly for a file
maze_runner_test.cpp.s:
	$(MAKE) -f CMakeFiles/maze_runner_test.dir/build.make CMakeFiles/maze_runner_test.dir/maze_runner_test.cpp.s
.PHONY : maze_runner_test.cpp.s

timer.o: timer.cpp.o

.PHONY : timer.o

# target to build an object file
timer.cpp.o:
	$(MAKE) -f CMakeFiles/disjointset_tester.dir/build.make CMakeFiles/disjointset_tester.dir/timer.cpp.o
.PHONY : timer.cpp.o

timer.i: timer.cpp.i

.PHONY : timer.i

# target to preprocess a source file
timer.cpp.i:
	$(MAKE) -f CMakeFiles/disjointset_tester.dir/build.make CMakeFiles/disjointset_tester.dir/timer.cpp.i
.PHONY : timer.cpp.i

timer.s: timer.cpp.s

.PHONY : timer.s

# target to generate assembly for a file
timer.cpp.s:
	$(MAKE) -f CMakeFiles/disjointset_tester.dir/build.make CMakeFiles/disjointset_tester.dir/timer.cpp.s
.PHONY : timer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... maze_runner_test"
	@echo "... disjointset_tester"
	@echo "... maze_generator_test"
	@echo "... disjointset.o"
	@echo "... disjointset.i"
	@echo "... disjointset.s"
	@echo "... disjointset_test.o"
	@echo "... disjointset_test.i"
	@echo "... disjointset_test.s"
	@echo "... maze.o"
	@echo "... maze.i"
	@echo "... maze.s"
	@echo "... maze_generator.o"
	@echo "... maze_generator.i"
	@echo "... maze_generator.s"
	@echo "... maze_generator_test.o"
	@echo "... maze_generator_test.i"
	@echo "... maze_generator_test.s"
	@echo "... maze_runner.o"
	@echo "... maze_runner.i"
	@echo "... maze_runner.s"
	@echo "... maze_runner_test.o"
	@echo "... maze_runner_test.i"
	@echo "... maze_runner_test.s"
	@echo "... timer.o"
	@echo "... timer.i"
	@echo "... timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

